[package]
name = "futils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = "*"
getopt = "*"
nix = "*"
regex = "*"
rustc_lexer = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tempfile = "*"
users = "*"
walkdir = "*"
