[package]
name = "futils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

atty = "*"
chrono = "*"
getopt = "*"
itertools ="*"
lazy_static = "*"
libc = "*"
nix = "*"
regex = "*"
rustc_lexer = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tempfile = "*"
users = "*"
walkdir = "*"

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
